### ISSUE TITLE
Mainline?

### ISSUE THREAD

**Issue by paultag** [patjak/mba6x_bl#10]
Any chance this could be mainlined?

Thanks!

**Comment by atodorov** [comment]
Any update on this one ?

**Comment by patjak** [comment]
The driver contains a few bugs that I haven't been able to solve so progress been stalled. It looks like the SMC (EC) programs the backlight chip on DPMS on/off (or related event from GPU) so it enters a faulty state. I need to figure out how to catch interrupts from the EC and reprogram the backlight when this happens. I need to sort this out before mainlining the driver.

**Comment by agimenez** [comment]
@patjak need help/information on this? I'd love to see this mainlined!

OTOH, this driver was born as a workaround, right? should not be the inter driver be fixed? Is that possible?

**Comment by patjak** [comment]
@agimenez what needs to be figured out before mainlining is what triggers the system firmware to reprogram the lp8550 (backlight chip) and how we can detect that and reprogram it since the firmware is messed up somehow. If we could figure out what the root problem is with the firmware would ofc be even better but I don't think Apple cares and they are the only ones releasing the firmware. Trying to work around this in i915 (intel driver) isn't a good idea since this is a platform problem and not a driver problem.

What I think is going on is that when i915 touches backlight registers the system firmware detects this and the SMC (embedded controller) kicks in and tries to program the lp8550. This is not what we want since the lp8550 is in a broken state after resume. We need a way to detect when this happens and make things right.

**Comment by agimenez** [comment]
I'm not used to work with that kind of hardware. My knowledge is quite limited, but if I can help somehow (I have some "basic" kernel hacking knowledge) please let me know.

What I don't get is why in OS X it works. Does it mean that Apple's firmware is doing nasty stuff to the chip, setting it in a wrong state, and their drivers know how to "get out" of that nasty state?

**Comment by patjak** [comment]
The fix in OSX could be in the graphics driver (i915 in our case). They don't need to care as much about stuff like that but since I don't understand the root cause of the problem it might be that they don't even have this issue.

**Comment by patjak** [comment]
I've decided not to mainline this since it's too much of a hack. Hopefully we wont have this problem on the next gen of MBAs.
